# Generated by Django 4.0.6 on 2022-07-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classTeacherOf', to='product.teacher')),
                ('favouriteTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favouriteTeacherOf', to='product.teacher')),
            ],
        ),
    ]
