# Generated by Django 4.0.6 on 2022-07-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_teacher_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
